# Generated by Django 4.2.2 on 2024-06-21 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changetype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('carimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('datecompleted_manager_approval', models.DateTimeField(blank=True, null=True)),
                ('datecompleted_client_approval', models.DateTimeField(blank=True, null=True)),
                ('datecompleted_history', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(max_length=1)),
                ('description', models.TextField(blank=True)),
                ('important', models.BooleanField(default=False)),
                ('deniedbyclient', models.BooleanField(default=False)),
                ('windows', models.BooleanField(default=False)),
                ('chassis', models.BooleanField(default=False)),
                ('wheels', models.BooleanField(default=False)),
                ('upholstery', models.BooleanField(default=False)),
                ('comentario_rechazo_cliente', models.TextField(blank=True, null=True)),
                ('flag_rechazado', models.BooleanField(default=False)),
                ('carbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.carbrand')),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.carmodel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.client')),
                ('employee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user_for_task', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.project')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_user_for_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sgmaq.task')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changereason', models.CharField(max_length=100)),
                ('changetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.changetype')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofchange', models.DateTimeField(auto_now_add=True)),
                ('descripcion_estado', models.TextField(blank=True, null=True)),
                ('changereason', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
