# Generated by Django 4.2.2 on 2024-06-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgmaq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comentario_rechazo_manager',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='motivo_rechazo_cliente',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='motivo_rechazo_manager',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True),
        ),
    ]
